Traceback (most recent call last):
  File "/home/runner/.local/lib/python3.12/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/home/runner/.local/lib/python3.12/site-packages/nbclient/client.py", line 1305, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/.local/lib/python3.12/site-packages/jupyter_core/utils/__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/asyncio/base_events.py", line 687, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/home/runner/.local/lib/python3.12/site-packages/nbclient/client.py", line 705, in async_execute
    await self.async_execute_cell(
  File "/home/runner/.local/lib/python3.12/site-packages/nbclient/client.py", line 1058, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/home/runner/.local/lib/python3.12/site-packages/nbclient/client.py", line 914, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
try:
    cadence_labels = D.get_feature("cadencelabels")
except Exception:
    raise ValueError("Corpus has no cadence annotations.")
cadence_labels
------------------


[31m---------------------------------------------------------------------------[39m
[31mRuntimeError[39m                              Traceback (most recent call last)
[36mCell[39m[36m [39m[32mIn[4][39m[32m, line 2[39m
[32m      1[39m [38;5;28;01mtry[39;00m:
[32m----> [39m[32m2[39m     cadence_labels = [43mD[49m[43m.[49m[43mget_feature[49m[43m([49m[33;43m"[39;49m[33;43mcadencelabels[39;49m[33;43m"[39;49m[43m)[49m
[32m      3[39m [38;5;28;01mexcept[39;00m [38;5;167;01mException[39;00m:

[36mFile [39m[32m~/.local/lib/python3.12/site-packages/dimcat/data/datasets/base.py:314[39m, in [36mDataset.get_feature[39m[34m(self, feature)[39m
[32m    313[39m     [38;5;28;01mpass[39;00m
[32m--> [39m[32m314[39m [38;5;28;01mreturn[39;00m [38;5;28;43mself[39;49m[43m.[49m[43mextract_feature[49m[43m([49m[43mfeature_config[49m[43m)[49m

[36mFile [39m[32m~/.local/lib/python3.12/site-packages/dimcat/data/datasets/base.py:290[39m, in [36mDataset.extract_feature[39m[34m(self, feature, ignore_exceptions)[39m
[32m    289[39m feature_extractor = Constructor(feature_config)
[32m--> [39m[32m290[39m extracted = [38;5;28;43mself[39;49m[43m.[49m[43m_extract_feature[49m[43m([49m
[32m    291[39m [43m    [49m[43mfeature_config[49m[43m,[49m[43m [49m[43mignore_exceptions[49m[43m=[49m[43mignore_exceptions[49m
[32m    292[39m [43m[49m[43m)[49m
[32m    293[39m [38;5;28mself[39m.add_output(resource=extracted, package_name=[33m"[39m[33mfeatures[39m[33m"[39m)

[36mFile [39m[32m~/.local/lib/python3.12/site-packages/dimcat/data/datasets/base.py:259[39m, in [36mDataset._extract_feature[39m[34m(self, feature_config, ignore_exceptions)[39m
[32m    249[39m [38;5;250m[39m[33;03m"""Extracts a feature from the Dataset's input catalog, sends it through its pipeline and returns the result,[39;00m
[32m    250[39m [33;03mwithout storing it.[39;00m
[32m    251[39m 
[32m   (...)[39m[32m    257[39m [33;03m        extracted feature, ignoring the fact that not all PipelineSteps may have been applied to it.[39;00m
[32m    258[39m [33;03m"""[39;00m
[32m--> [39m[32m259[39m extracted = [38;5;28;43mself[39;49m[43m.[49m[43minputs[49m[43m.[49m[43mextract_feature[49m[43m([49m[43mfeature_config[49m[43m)[49m
[32m    260[39m [38;5;28;01mif[39;00m [38;5;28mlen[39m([38;5;28mself[39m._pipeline) == [32m0[39m:

[36mFile [39m[32m~/.local/lib/python3.12/site-packages/dimcat/data/catalogs/inputs.py:18[39m, in [36mInputsCatalog.extract_feature[39m[34m(self, feature)[39m
[32m     17[39m package = [38;5;28mself[39m.get_package()
[32m---> [39m[32m18[39m [38;5;28;01mreturn[39;00m [43mpackage[49m[43m.[49m[43mextract_feature[49m[43m([49m[43mfeature[49m[43m)[49m

[36mFile [39m[32m~/.local/lib/python3.12/site-packages/dimcat/data/packages/base.py:1047[39m, in [36mPackage.extract_feature[39m[34m(self, feature)[39m
[32m   1046[39m selected_facet = candidate_facets[[32m0[39m]
[32m-> [39m[32m1047[39m [38;5;28;01mreturn[39;00m [43mselected_facet[49m[43m.[49m[43m_extract_feature[49m[43m([49m[43mfeature_config[49m[43m)[49m

[36mFile [39m[32m~/.local/lib/python3.12/site-packages/dimcat/data/resources/dc.py:985[39m, in [36mDimcatResource._extract_feature[39m[34m(self, feature_config, new_name)[39m
[32m    984[39m len_before = [38;5;28mlen[39m(feature_df)
[32m--> [39m[32m985[39m feature_df = [38;5;28;43mself[39;49m[43m.[49m[43m_transform_df_for_extraction[49m[43m([49m[43mfeature_df[49m[43m,[49m[43m [49m[43mfeature_config[49m[43m)[49m
[32m    986[39m init_args = [38;5;28mdict[39m(
[32m    987[39m     resource_name=new_name,
[32m    988[39m )

[36mFile [39m[32m~/.local/lib/python3.12/site-packages/dimcat/data/resources/facets.py:808[39m, in [36mMuseScoreHarmonies._transform_df_for_extraction[39m[34m(self, feature_df, feature_config)[39m
[32m    807[39m [38;5;28;01mif[39;00m [38;5;28missubclass[39m([38;5;28mcls[39m, CadenceLabels):
[32m--> [39m[32m808[39m     feature_df = [43mdrop_rows_with_missing_values[49m[43m([49m
[32m    809[39m [43m        [49m[43mfeature_df[49m[43m,[49m[43m [49m[43mfeature_column_names[49m[43m,[49m[43m [49m[43mlogger[49m[43m=[49m[38;5;28;43mself[39;49m[43m.[49m[43mlogger[49m
[32m    810[39m [43m    [49m[43m)[49m
[32m    811[39m     feature_df = extend_cadence_feature(feature_df)

[36mFile [39m[32m~/.local/lib/python3.12/site-packages/dimcat/data/resources/utils.py:435[39m, in [36mdrop_rows_with_missing_values[39m[34m(df, column_names, how, logger)[39m
[32m    434[39m [38;5;28;01mif[39;00m drop_mask.all():
[32m--> [39m[32m435[39m     [38;5;28;01mraise[39;00m [38;5;167;01mRuntimeError[39;00m(
[32m    436[39m         [33mf[39m[33m"[39m[33mThe dataframe contains no fully defined objects based on the [39m[33m"[39m
[32m    437[39m         [33mf[39m[33m"[39m[33mcolumns [39m[38;5;132;01m{[39;00mcolumn_names[38;5;132;01m}[39;00m[33m.[39m[33m"[39m
[32m    438[39m     )
[32m    439[39m n_dropped = drop_mask.sum()

[31mRuntimeError[39m: The dataframe contains no fully defined objects based on the columns ['cadence'].

During handling of the above exception, another exception occurred:

[31mValueError[39m                                Traceback (most recent call last)
[36mCell[39m[36m [39m[32mIn[4][39m[32m, line 4[39m
[32m      2[39m     cadence_labels = D.get_feature([33m"[39m[33mcadencelabels[39m[33m"[39m)
[32m      3[39m [38;5;28;01mexcept[39;00m [38;5;167;01mException[39;00m:
[32m----> [39m[32m4[39m     [38;5;28;01mraise[39;00m [38;5;167;01mValueError[39;00m([33m"[39m[33mCorpus has no cadence annotations.[39m[33m"[39m)
[32m      5[39m cadence_labels

[31mValueError[39m: Corpus has no cadence annotations.

